steps:

  - name: 'maven:3.9-eclipse-temurin-17'
    entrypoint: 'mvn'
    args:
      - 'clean'
      - 'test'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/order-service:$SHORT_SHA'
      - './order-service'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/order-service:$SHORT_SHA'

substitutions:
  _REGION: 'asia-south1'
  _REPOSITORY: 'cloud-order-platform'

images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/order-service:$SHORT_SHA'