apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
  namespace: cloud-order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
        - name: config-server
          image: cloudorder/config-server:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8888