apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: cloud-order
spec:
  selector:
    app: api-gateway
  ports:
    - port: 8085
      targetPort: 8085
      nodePort: 30080
  type: NodePort