spring:
  application:
    name: inventory-service

  kafka:
    bootstrap-servers: localhost:9092
    listener:
      missing-topics-fatal: false
    consumer:
      group-id: inventory-service
      auto-offset-reset: earliest

      key-deserializer:
        org.apache.kafka.common.serialization.StringDeserializer

      value-deserializer:
        org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.trusted.packages: "com.cloudorder.inventory.event"
        spring.json.value.default.type: "com.cloudorder.inventory.event.OrderCreatedEvent"

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics