apiVersion: v1
kind: ServiceAccount
metadata:
  name: order-service
  namespace: cloud-order
  annotations:
    iam.gke.io/gcp-service-account:  order-service@cloud-order-platform.iam.gserviceaccount.com