apiVersion: apps/v1
kind: Deployment
metadata:
  name: dynamodb
  namespace: cloud-order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dynamodb
  template:
    metadata:
      labels:
        app: dynamodb
    spec:
      containers:
        - name: dynamodb
          image: amazon/dynamodb-local:latest
          args:
            - "-jar"
            - "DynamoDBLocal.jar"
            - "-sharedDb"
            - "-inMemory"
          ports:
            - containerPort: 8000